### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by Veetaha** [dtolnay/async-trait#122]
Hey, looks like the crate is mature enough for reaching `1.0`. isn't it?

**Comment by taiki-e** [comment]
Before doing this, we might want to compare the current approach of expanding an async method into a normal method + async functions with the approach of expanding an async method into a normal method + an async block.
As far as I know, the latter can solve existing problems such as #8, #61, and #126, but it can cause some other problems such as drop-order.

**Comment by jocutajar** [comment]
I am a bit confused to be honest. I'd like to understand the real world implications of dropping unused variables. This is not destructor drop order which, I understand, is quite sensitive. If a mutex is unused, it should be dropped. And if it changes the behavior which should not be relied on in my opinion, then perhaps a major release will signal the change? Throwing away such a major improvement and simplification just because a minor change in behavior is in my opinion inadequate.

**Comment by qm3ster** [comment]
It is now CURRENT_YEAR, perhaps we can start preparing for `min_type_alias_impl_trait`? For example by having a `nightly` feature flag that generates code with associated types instead of `Box<dyn`?
Something like this:
```rust
#![feature(min_type_alias_impl_trait)]
use core::future::Future;
trait Bepis<'s> {
    type F: Future<Output = String>;
    fn ie(&'s mut self) -> Self::F;
}
struct B(String);
struct C();
impl<'s> Bepis<'s> for B {
    type F = impl Future<Output = String> + 's;
    fn ie(&'s mut self) -> Self::F {
        async move { std::mem::take(&mut self.0) }
    }
}
impl<'s> Bepis<'s> for C {
    type F = impl Future<Output = String> + 's;
    fn ie(&'s mut self) -> Self::F {
        async { "traid".into() }
    }
}
#[tokio::main]
async fn main() {
    let mut b = B("asyng".into());
    println!("{}", Bepis::ie(&mut b).await);
    println!("{}", b.0);
    println!("{}", Bepis::ie(&mut C()).await);
}
```
(sorry if this makes no sense, I am not a scientist)

**Comment by dtolnay** [comment]
I think 0.1 accurately indicates the level of maturity of this crate for the foreseeable future, so I am closing this issue.
