### ISSUE TITLE
cargo doc generates ugly documentation

### ISSUE THREAD

**Issue by nullchinchilla** [dtolnay/async-trait#213]
`cargo doc` seems to generate documentation for the trait based on the expanded code, rather than the pre-expansion code. e.g.

![image](https://user-images.githubusercontent.com/20490891/185035034-dab7d46c-3757-4fc2-aedf-fd33fd615f28.png)

Is this fundamentally unfixable, or is there some way of getting `cargo doc` to display the trait with the pre-expansion form, document the methods as `async fn` etc?

**Comment by dtolnay** [comment]
This would need to be a feature request for rustdoc to support emitting async fn in traits. Currently there is no way.

**Comment by nullchinchilla** [comment]
That is very unfortunate. Is the only way manually documenting the `async fn`s then?

**Comment by dtolnay** [comment]
Yeah you can do:

```toml
# Cargo.toml

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docs_rs"]
```

```rust
// lib.rs

#![cfg_attr(docs_rs, feature(async_fn_in_trait))]

#[cfg_attr(not(docs_rs), async_trait::async_trait)]
pub trait Trait {
    async fn f();
}
```

<img src="https://github.com/dtolnay/async-trait/assets/1940490/a77f8996-6606-47c0-a7e2-cbf507885463" width="350">

**Comment by eaufavor** [comment]
I don't think this doc trick works universally anymore since the official async trait is stabilized but with a lot [limitations](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#dynamic-dispatch).  In other words, some of the traits I created are not valid (can no longer compile) under the official async trait. So it might be the time to reconsider this ticket.
