### ISSUE TITLE
Generic params from impl dont have 'async_trait lifetime

### ISSUE THREAD

**Issue by kpp** [dtolnay/async-trait#8]
I tried to produce a MRE:

```
#[async_trait]
pub trait MapInto<T>: Future {
    async fn map_into(self) -> T
        where Self: Sized;
}

#[async_trait]
impl<F, T> MapInto<T> for F
    where F: ?Sized,
          F: Future + Send,
          T: From<F::Output>,
{
    async fn map_into(self) -> T
        where Self: Sized,
    {
        self.await.into()
    }
}

error:

error[E0309]: the parameter type `T` may not live long enough
   --> src/future.rs:116:1
    |
116 | #[async_trait]
    | ^^^^^^^^^^^^^^
117 | impl<F, T> MapInto<T> for F
    |         - help: consider adding an explicit lifetime bound `T: 'async_trait`...
    |
```

A fix for me: `T: 'static,` in impl block. Is it a bug?

**Comment by dtolnay** [comment]
Thanks! I don't know how to fix this best, since I don't want to infer overly restrictive bounds by default -- it's always possible for the user of the macro to add extra bounds as necessary, but there isn't a good way for them to subtract bounds that aren't right. I found that inferring `_: 'async_trait` for every generic parameter on the impl block tends to be too restrictive.

I would recommend adding your own `T: 'async_trait` bound (not `T: 'static`) when you see a compiler error like that one.

```rust
#[async_trait]
pub trait MapInto<T>: Future {
    async fn map_into(self) -> T
    where
        Self: Sized,
        T: 'async_trait;
}

#[async_trait]
impl<F, T> MapInto<T> for F
where
    F: ?Sized + Future + Send,
    T: From<F::Output>,
{
    async fn map_into(self) -> T
    where
        Self: Sized,
        T: 'async_trait,
    {
        self.await.into()
    }
}
```

That bound basically means "`T` lives \\"long enough\\"". To explain the underlying lifetime logic a bit:

- *The caller* of an async trait method gets to choose any lifetime to use as `'async_trait` for that call;

- We require *the caller* of the async trait method to guarantee that all arguments they pass outlive `'async_trait`;

- In return, we require that *the implementer* of the async trait method guarantee that the returned future outlives `'async_trait`.

So for example, if the caller wants to get back a `'static` future, then they must pass in arguments that are all `'static`. This system reflects rustc's lifetime rules for return position impl Trait and async fn.

**Comment by kpp** [comment]
> I would recommend adding your own T: 'async_trait bound (not T: 'static) when you see a compiler error like that one.

Then I will have to add a lot of `T: 'async_trait, E: 'async_trait` into my methods =)

**Comment by Ekleog** [comment]
FWIW, here is a more minimal example:
```rust
#[async_trait::async_trait]
pub trait Trait<T> {
    async fn foo() {
        ()
    }
}
```

Seeing as such a trivial example already fails the `T: 'async_trait` bound… I'd be curious in which cases the bound would not be required?

**Comment by taiki-e** [comment]
FYI: currently, it seems functions that return impl traits capture all generic type parameters in function's generics, whether they are actually used or not. (probably related to [rfc1951](https://github.com/rust-lang/rfcs/blob/master/text/1951-expand-impl-trait.md#the-proposal-in-a-nutshell)) 
For example:

```rust
pub trait Trait<T> {
    fn method<'lt>() -> Box<dyn ::core::fmt::Debug + 'lt>;
}

impl<T> Trait<T> for usize {
    fn method<'lt>() -> Box<dyn ::core::fmt::Debug + 'lt> {
        fn __method<'lt, T>() -> impl ::core::fmt::Debug + 'lt {}
        Box::new(__method::<T>())
        //~^ ERROR the parameter type `T` may not live long enough
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7c0c608e2a3111f6e240328df97288ad)

In the current implementation of async-trait, the generated freestanding function's generics is impl's generics + method's generics, so it seems that all generic type parameters actually require (at least `'async_trait`) lifetime bounds.

Also, this seems to be specific to generic type parameters of functions that return impl traits, for example, it doesn't apply to [lifetime definitions of functions that return impl traits](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0717c5d2416869d62cf7cf96613d1c1e) or [generic type parameters of functions that return normal values](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b76a01426540a4b409a24dea7063b86).

(I wrote this comment because I wasn't sure if https://github.com/dtolnay/async-trait/issues/8#issuecomment-514812245 was written with this in mind. I'm sorry if I misread your comment.)

**Comment by Koxiaet** [comment]
I'm having a similar issue, but unfortunately this isn't as easily fixable:

```rust
#[async_trait]
trait Trait {
    async fn func(&self);
}

struct Struct<R>(R);

#[async_trait]
impl<R: Deref<Target = Option<T>> + Send + Sync, T: Send + Sync> Trait for Struct<R> {
    async fn func(&self) {
        //               ^ [rustc E0309] [E] the parameter type `R2` may not live long enough
    }
}
```

I can't add `'async_trait` to `T` because it doesn't exist at the item scope yet, and I don't want to have to make `T: 'static`. Is there there a fix for this?

**Comment by taiki-e** [comment]
@Koxiaet A workaround that I know is adding lifetime to trait: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e977da3ddc0c21639b3116e123a94b6f)

**Comment by the-notable** [comment]
I'm getting the same error, but with default impl directly in declaration:

```rust
#[async_trait]
trait Trait <T: Send>: Struct {
    async fn assoc_func<U>(n: Vec<T>) -> CustomResult<'_, Vec<U>> {
        call_async_func().await
    }
}
```

Produces:

```
error[E0309]: the parameter type `T` may not live long enough
  --> src/model/mod.rs:84:113
   |
83 |   trait Trait<T: Send>: Struct {
   |               -------- help: consider adding an explicit lifetime bound...: `T: 'async_trait +`
84 |       async fn assoc_func<U>(n: Vec<T>) -> CustomResult<'_, Vec<U>> {
   |  ___________________________________________________________________^
85 | |         call_async_func().await
86 | |     }
   | |_____^ ...so that the type `impl core::future::future::Future` will meet its required lifetime bounds

```

Addind `'async_trait` lifetime to trait: 

```rust
#[async_trait]
trait Trait <T: 'async_trait + Send>: Struct {
    async fn assoc_func<U>(n: Vec<T>) -> CustomResult<'_, Vec<U>> {
        call_async_func().await
    }
}
```

Results in:

```
error[E0261]: use of undeclared lifetime name `'async_trait`
  --> src/model/mod.rs:83:28
   |
83 | pub trait Trait<T: 'async_trait + Send>: Struct{
   |                 -  ^^^^^^^^^^^^ undeclared lifetime
   |                 |
   |                 help: consider introducing lifetime `'async_trait` here: `'async_trait,`

```

**Comment by taiki-e** [comment]
@dtolnay: I think this issue has been fixed by https://github.com/dtolnay/async-trait/pull/143: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=47749bbe8228cfef6c8b023b41c4c6fd)

**Comment by dtolnay** [comment]
Nice!

**Comment by jaskij** [comment]
Sadly, I'm still getting this issue, in a more complicated case ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b13997fc9e0a52ea4dfc08377601ea80), MRE below). The provided workaround of adding `'async_trait` works just fine.

It seems to be some more complex interaction of types, because removing the `_output` parameter, or removing the default implementation both get rid of the error.

```rust
use async_trait::async_trait;
use tokio::sync::mpsc;

#[async_trait]
trait InputStage<StageOutput>: Sized
where
    StageOutput: Send,
{
    async fn run(
        mut self,
        _output: mpsc::Sender<StageOutput>,
    )
    //where StageOutput: 'async_trait,
    {

    }
}
```
